//
//  SearchLeaderController.swift
//  RecordTableView
//
//  Created by おじぇ on 2022/10/21.
//

import UIKit

//親画面に値を渡すためのプロトコル宣言
protocol DataReturn {
    func store(data: String)
}

class SearchLeaderController: UIViewController,UITableViewDelegate,UITableViewDataSource,UITextFieldDelegate {
    @IBOutlet weak var leaderTableView: UITableView!
    @IBOutlet weak var searchLeaderLabel: UITextField!
    
    private var allDatas = [String]()
    private var filterdDatas = [String]()
    var paramLeader:String = ""  //親画面からのパラメータ
    var selectedRow:Int? = nil
    
    var delegate: DataReturn?  //親に値を渡す用
    

    override func viewDidLoad() {
        super.viewDidLoad()
        searchLeaderLabel.placeholder = "Search..."
        
        //allDatas = createCMDList()  //全リーダー名を呼び出して配列に設定
        allDatas = TabBarController.commanderNameList  //全リーダー名を保持
        
        searchLeaderLabel.addTarget(self,action: #selector(textFieldDidChange(_:)), for:.editingChanged)  //値が変わるたびに呼び出す関数を設定
        
        //親画面のテキストフィールドに値があれば、絞り込み実施と、その行を選択状態にする
        if(paramLeader != ""){
            searchLeaderLabel.text = paramLeader
            filterText(paramLeader)  //絞り込み
            if(filterdDatas.contains(paramLeader)){
                leaderTableView.selectRow(at: IndexPath(row:0, section:0), animated:true, scrollPosition:.none)  //0番目を選択状態にする
                selectedRow = 0
            }
        }
        
        searchLeaderLabel.becomeFirstResponder()  //フォーカスをオンにする
    }
    
    //---------------------------イベント処理の記述
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if(searchLeaderLabel.text! == ""){
            return allDatas.count
        }
        return filterdDatas.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "leaderCell", for: indexPath)
        cell.textLabel?.text = filterdDatas.isEmpty ? allDatas[indexPath.row] : filterdDatas[indexPath.row]
        return cell
    }
    
    //tableがスクロール開始されたときに呼ばれる
    func scrollViewWillBeginDragging(_ scrollView:UIScrollView){
        searchLeaderLabel.resignFirstResponder()  //キーボードを閉じる
    }
    
    //セルが選択されたときに実行される処理
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let idx = indexPath.row
        
        //選択済みの行をタップした場合は選択を解除する
        if(selectedRow != nil && selectedRow == idx){
            tableView.deselectRow(at: IndexPath(row: idx, section: 0), animated: true)  //選択解除
            selectedRow = nil
        }else{
            selectedRow = idx
        }
        
        /*
        if(searchLeaderLabel.text! == ""){
            searchLeaderLabel.text = allDatas[idx]
        }else{
            searchLeaderLabel.text = filterdDatas[idx]
        }
        filterText(searchLeaderLabel.text!)  //フィルタ実行
        */
    }
    
    //テキストフィールドの値が変わるたびに呼び出される処理
    @objc func textFieldDidChange(_ textField: UITextField){
        if let text = textField.text{
            filterText(text)
            selectedRow = nil
        }
    }
    
    //Doneボタン押下時の処理
    @IBAction func doneAct(_ sender: Any) {
        var selectedName = ""
        
        if let idx = leaderTableView.indexPathForSelectedRow {
            selectedName = searchLeaderLabel.text! == "" ? allDatas[idx.row] : filterdDatas[idx.row]
        }
        
        delegate?.store(data: selectedName)  //選択したリーダー名をデリゲートに設定(モーダル画面を閉じたあと親側で取得する)
        dismiss(animated: true, completion: nil)  //モーダル画面を閉じる
        
    }
    
    //-------------------------関数------------------------
    
    //引数の文字と先頭が一致する文字をfilterdDatasに追加する
    func filterText(_ query: String) {
        filterdDatas.removeAll()
        allDatas.forEach{ data in
            if data.lowercased().starts(with: query.lowercased()){
                filterdDatas.append(data)
            }
        }
        leaderTableView.reloadData()
    }
    
    //全リーダー名を配列にする関数
    /*func createCMDList() -> [String] {
        let cmdList = [
            "Abdel Adrian, Gorion's Ward",
            "Abomination of Llanowar",
            "Acererak the Archlich",
            "Adamaro, First to Desire",
            "Adeline, Resplendent Cathar",
            "Adeliz, the Cinder Wind",
            "Admiral Beckett Brass",
            "Adriana, Captain of the Guard",
            "Adrix and Nev, Twincasters",
            "Aegar, the Freezing Flame",
            "Aesi, Tyrant of Gyre Strait",
            "Aeve, Progenitor Ooze",
            "Agrus Kos, Wojek Veteran",
            "Akim, the Soaring Wind",
            "Akiri, Fearless Voyager",
            "Akiri, Line-Slinger",
            "Akroma, Angel of Fury",
            "Akroma, Angel of Wrath",
            "Akroma, Vision of Ixidor",
            "Akuta, Born of Ash",
            "Alaundo the Seer",
            "Alela, Artful Provocateur",
            "Alena, Kessig Trapper",
            "Alesha, Who Smiles at Death",
            "Alhammarret, High Arbiter",
            "Alharu, Solemn Ritualist",
            "Alibou, Ancient Witness",
            "Alirios, Enraptured",
            "Alora, Merry Thief",
            "Alrund, God of the Cosmos",
            "Amareth, the Lustrous",
            "Ambassador Laquatus",
            "Amber Gristle O'Maul",
            "Anafenza, Kin-Tree Spirit",
            "Anafenza, the Foremost",
            "Anara, Wolvid Familiar",
            "Anax and Cymede",
            "Anax, Hardened in the Forge",
            "Anhelo, the Painter",
            "Animar, Soul of Elements",
            "Anje Falkenrath",
            "Anje, Maid of Dishonor",
            "Anowon, the Ruin Sage",
            "Anowon, the Ruin Thief",
            "Anrakyr the Traveller",
            "Anthousa, Setessan Hero",
            "Anya, Merciless Angel",
            "Ao, the Dawn Sky",
            "Aphemia, the Cacophony",
            "Arahbo, Roar of the World",
            "Arashi, the Sky Asunder",
            "Arasta of the Endless Web",
            "Araumi of the Dead Tide",
            "Arcades, the Strategist",
            "Arcanis the Omnipotent",
            "Archangel Avacyn",
            "Archelos, Lagoon Mystic",
            "Arcum Dagsson",
            "Ardenn, Intrepid Archaeologist",
            "Arixmethes, Slumbering Isle",
            "Arjun, the Shifting Flame",
            "Armix, Filigree Thrasher",
            "Arni Brokenbrow",
            "Aron, Benalia's Ruin",
            "Arvad the Cursed",
            "Aryel, Knight of Windgrace",
            "Ascendant Evincar",
            "Ashaya, Soul of the Wild",
            "Ashling the Pilgrim",
            "Ashling, the Extinguisher",
            "Asmodeus the Archfiend",
            "Asmoranomardica daistinaculdacar",  //空白追加
            "Astarion, the Decadent",
            "Astor, Bearer of Blades",
            "Atarka, World Render",
            "Atemsis, All-Seeing",
            "Athreos, God of Passage",
            "Athreos, Shroud-Veiled",
            "Atla Palani, Nest Tender",
            "Atraxa, Praetors' Voice",
            "Atris, Oracle of Half-Truths",
            "Atsushi, the Blazing Sky",
            "Augusta, Dean of Order",
            "Aurelia, Exemplar of Justice",
            "Aurelia, the Warleader",
            "Autumn-Tail, Kitsune Sage",
            "Avacyn, Angel of Hope",
            "Avacyn, Guardian Angel",
            "Avacyn, the Purifier",
            "Averna, the Chaos Bloom",
            "Ayara, First of Locthwain",
            "Ayli, Eternal Pilgrim",
            "Ayula, Queen Among Bears",
            "Ayumi, the Last Visitor",
            "Azami, Lady of Scrolls",
            "Azamuki, Treachery Incarnate",
            "Azor, the Lawbringer",
            "Azusa, Lost but Seeking",
            "Baba Lysaga, Night Witch",
            "Baeloth Barrityl, Entertainer",
            "Baird, Argivian Recruiter",
            "Baird, Steward of Argive",
            "Balan, Wandering Knight",
            "Balmor, Battlemage Captain",
            "Bane, Lord of Darkness",
            "Baral, Chief of Compliance",
            "Barrin, Tolarian Archmage",
            "Barrowin of Clan Undurr",
            "Baru, Fist of Krosa",
            "Baru, Wurmspeaker",
            "Basandra, Battle Seraph",
            "Belbe, Corrupted Observer",
            "Beledros Witherbloom",
            "Belisarius Cawl",
            "Bell Borca, Spectral Sergeant",
            "Ben-Ben, Akki Hermit",
            "Bennie Bracks, Zoologist",
            "Bess, Soul Nourisher",
            "Bhaal, Lord of Murder",
            "Birgi, God of Storytelling",
            "Bladewing the Risen",
            "Bladewing, Deathless Tyrant",
            "Blex, Vexing Pest",
            "Blim, Comedic Genius",
            "Bontu the Glorified",
            "Borborygmos",
            "Borborygmos Enraged",
            "Bortuk Bonerattle",
            "Bosh, Iron Golem",
            "Bounteous Kirin",
            "Brago, King Eternal",
            "Braids, Arisen Nightmare",
            "Braids, Cabal Minion",
            "Braids, Conjurer Adept",
            "Brallin, Skyshark Rider",
            "Breeches, Brazen Plunderer",
            "Breena, the Demagogue",
            "Breya, Etherium Shaper",
            "Brigid, Hero of Kinsbaile",
            "Brimaz, King of Oreskos",
            "Brinelin, the Moon Kraken",
            "Brion Stoutarm",
            "Brisela, Voice of Nightmares",
            "Brokkos, Apex of Forever",
            "Brothers Yamazaki",
            "Brudiclad, Telchor Engineer",
            "Bruenor Battlehammer",
            "Bruna, Light of Alabaster",
            "Bruna, the Fading Light",
            "Bruse Tarl, Boorish Herder",
            "Burakos, Party Leader",
            "Cadira, Caller of the Small",
            "Cadric, Soul Kindler",
            "Callaphe, Beloved of the Sea",
            "Captain Lannery Storm",
            "Captain N'ghathrod",
            "Captain Ripley Vance",
            "Captain Vargus Wrath",
            "Carth the Lion",
            "Catti-brie of Mithral Hall",
            "Cazur, Ruthless Stalker",
            "Celestial Kirin",
            "Celestine, the Living Saint",
            "Chainer, Nightmare Adept",
            "Chandra, Fire of Kaladesh",
            "Charix, the Raging Isle",
            "Chatterfang, Squirrel General",
            "Chevill, Bane of Monsters",
            "Child of Alara",
            "Chisei, Heart of Oceans",
            "Chishiro, the Shattered Blade",
            "Cho-Manno, Revolutionary",
            "Chorus of the Conclave",
            "Chromium, the Mutable",
            "Circu, Dimir Lobotomist",
            "Cloudhoof Kirin",
            "Codie, Vociferous Codex",
            "Colfenor, the Last Yew",
            "Commander Liara Portyr",
            "Commissar Severina Raine",
            "Cormela, Glamour Thief",
            "Cosima, God of the Voyage",
            "Crosis, the Purger",
            "Crovax, Ascendant Hero",
            "Daghatar the Adamant",
            "Dalakos, Crafter of Wonders",
            "Damia, Sage of Stone",
            "Danitha Capashen, Paragon",
            "Danitha, Benalia's Hope",
            "Dargo, the Shipwrecker",
            "Darien, King of Kjeldor",
            "Darigaaz Reincarnated",
            "Darigaaz, the Igniter",
            "Daxos of Meletis",
            "Daxos the Returned",
            "Daxos, Blessed by the Sun",
            "Deathleaper, Terror Weapon",
            "Deekah, Fractal Theorist",
            "Delina, Wild Mage",
            "Demonlord Belzenlok",
            "Dennick, Pious Apparition",
            "Dennick, Pious Apprentice",
            "Denry Klin, Editor in Chief",
            "Depala, Pilot Exemplar",
            "Derevi, Empyrial Tactician",
            "Dina, Soul Steeper",
            "Djeru, With Eyes Open",
            "Dokai, Weaver of Life",
            "Donal, Herald of Wings",
            "Doran, the Siege Tower",
            "Dorothea, Vengeful Victim",
            "Dosan the Falling Leaf",
            "Dragonlord Atarka",
            "Dragonlord Dromoka",
            "Dragonlord Kolaghan",
            "Dragonlord Ojutai",
            "Dragonlord Silumgar",
            "Drakuseth, Maw of Flames",
            "Dralnu, Lich Lord",
            "Drana, Kalastria Bloodchief",
            "Drana, Liberator of Malakir",
            "Drana, the Last Bloodchief",
            "Drizzt Do'Urden",
            "Dromoka, the Eternal",
            "Duke Ulder Ravengard",
            "Durnan of the Yawning Portal",
            "Dwynen, Gilt-Leaf Daen",
            "Dynaheir, Invoker Adept",
            "Ebondeath, Dracolich",
            "Edgar Markov",
            "Edgar, Charmed Groom",
            "Edric, Spymaster of Trest",
            "Egon, God of Death",
            "Eight-and-a-Half-Tails",
            "Elas il-Kor, Sadistic Pilgrim",
            "Elenda, the Dusk Rose",
            "Elesh Norn, Grand Cenobite",
            "Eligeth, Crossroads Augur",
            "Ellyn Harbreeze, Busybody",
            "Eloise, Nephalia Sleuth",
            "Elsha of the Infinite",
            "Embrose, Dean of Shadow",
            "Emiel the Blessed",
            "Emmara Tandris",
            "Emmara, Soul of the Accord",
            "Emperor Mihail II",
            "Emrakul, the Aeons Torn",
            "Emrakul, the Promised End",
            "Emry, Lurker of the Loch",
            "Endrek Sahr, Master Breeder",
            "Ephara, God of the Polis",
            "Erayo's Essence",
            "Erayo, Soratami Ascendant",
            "Erebos, Bleak-Hearted",
            "Erebos, God of the Dead",
            "Erinis, Gloom Stalker",
            "Eron the Relentless",
            "Errant, Street Artist",
            "Ertai Resurrected",
            "Eruth, Tormented Prophet",
            "Esika, God of the Tree",
            "Esior, Wardwing Familiar",
            "Esix, Fractal Bloom",
            "Etali, Primal Storm",
            "Etrata, the Silencer",
            "Eutropia the Twice-Favored",
            "Evelyn, the Covetous",
            "Evra, Halcyon Witness",
            "Exava, Rakdos Blood Witch",
            "Experiment Kraj",
            "Extus, Oriq Overlord",
            "Ezuri, Claw of Progress",
            "Ezuri, Renegade Leader",
            "Faceless One",
            "Fain, the Broker",
            "Falco Spara, Pactweaver",
            "Faldorn, Dread Wolf Herald",
            "Falthis, Shadowcat Familiar",
            "Farideh, Devil's Chosen",
            "Fblthp, the Lost",
            "Feather, the Redeemed",
            "Feldon of the Third Path",
            "Felisa, Fang of Silverquill",
            "Firesong and Sunspeaker",
            "Firja, Judge of Valor",
            "Firkraag, Cunning Instigator",
            "Florian, Voldaren Scion",
            "Fumiko the Lowblood",
            "Fynn, the Fangbearer",
            "Gaddock Teeg",
            "Gadrak, the Crown-Scourge",
            "Gadwick, the Wizened",
            "Gahiji, Honored One",
            "Galazeth Prismari",
            "Gale, Waterdeep Prodigy",
            "Galea, Kindler of Hope",
            "Gallia of the Endless Dance",
            "Ganax, Astral Hunter",
            "Gargos, Vicious Watcher",
            "Garna, Bloodfist of Keld",
            "Garna, the Bloodflame",
            "Garth One-Eye",
            "Garza Zol, Plague Queen",
            "Gavi, Nest Warden",
            "Geist of Saint Traft",
            "General Ferrous Rokiric",
            "General Kudro of Drannith",
            "General Tazri",
            "Geralf, Visionary Stitcher",
            "Gerrard Capashen",
            "Gerrard, Weatherlight Hero",
            "Geth, Lord of the Vault",
            "Ghalta, Primal Hunger",
            "Ghave, Guru of Spores",
            "Ghen, Arcanum Weaver",
            "Ghired, Conclave Exile",
            "Ghost Council of Orzhova",
            "Ghost of Ramirez DePietro",
            "Ghoulcaller Gisa",
            "Ghyrson Starn, Kelermorph",
            "Giada, Font of Hope",
            "Gilanra, Caller of Wirewood",
            "Gisa and Geralf",
            "Gisa, Glorious Resurrector",
            "Gisela, Blade of Goldnight",
            "Gisela, the Broken Blade",
            "Gishath, Sun's Avatar",
            "Glacian, Powerstone Engineer",
            "Glissa Sunseeker",
            "Glissa, the Traitor",
            "Gluntch, the Bestower",
            "Gnostro, Voice of the Crags",
            "Go-Shintai of Ancient Wars",
            "Go-Shintai of Boundless Vigor",
            "Go-Shintai of Hidden Cruelty",
            "Go-Shintai of Life's Origin",
            "Go-Shintai of Lost Wisdom",
            "Go-Shintai of Shared Purpose",
            "God-Eternal Bontu",
            "God-Eternal Kefnet",
            "God-Eternal Oketra",
            "God-Eternal Rhonas",
            "Godo, Bandit Warlord",
            "Goka the Unjust",
            "Golos, Tireless Pilgrim",
            "Gonti, Lord of Luxury",
            "Gor Muldrak, Amphinologist",
            "Goreclaw, Terror of Qal Sisma",
            "Gorex, the Tombshell",
            "Gorion, Wise Mentor",
            "Gorm the Great",
            "Goro-Goro, Disciple of Ryusei",
            "Grakmaw, Skyclave Ravager",
            "Grand Arbiter Augustin IV",
            "Grand Warlord Radha",
            "Grazilaxx, Illithid Scholar",
            "Greasefang, Okiba Boss",
            "Greensleeves, Maro-Sorcerer",
            "Grenzo, Dungeon Warden",
            "Grenzo, Havoc Raiser",
            "Gretchen Titchwillow",
            "Greven, Predator Captain",
            "Grimgrin, Corpse-Born",
            "Griselbrand",
            "Grismold, the Dreadsower",
            "Grolnok, the Omnivore",
            "Grothama, All-Devouring",
            "Grumgully, the Generous",
            "Grunn, the Lonely King",
            "Gut, True Soul Zealot",
            "Gwafa Hazid, Profiteer",
            "Gyome, Master Chef",
            "Gyruda, Doom of Depths",
            "Gyrus, Waker of Corpses",
            "Haakon, Stromgald Scourge",
            "Hakka, Whispering Raven",
            "Haktos the Unscarred",
            "Halana and Alena, Partners",
            "Halana, Kessig Ranger",
            "Haldan, Avid Arcanist",
            "Hallar, the Firefletcher",
            "Halsin, Emerald Archdruid",
            "Halvar, God of Battle",
            "Hama Pashar, Ruin Seeker",
            "Hamza, Guardian of Arashin",
            "Hanna, Ship's Navigator",
            "Hans Eriksson",
            "Hanweir, the Writhing Township",
            "Hapatra, Vizier of Poisons",
            "Harald, King of Skemfar",
            "Hazoret the Fervent",
            "He Who Hungers",
            "Heartless Hidetsugu",
            "Heidar, Rimewind Master",
            "Heiko Yamazaki, the General",
            "Heliod, God of the Sun",
            "Heliod, Sun-Crowned",
            "Henrika Domnathi",
            "Henrika, Infernal Seer",
            #"Henzie "Toolbox" Torre"#,
            "Hidetsugu, Devouring Chaos",
            "Higure, the Still Wind",
            "Hikari, Twilight Guardian",
            "Hinata, Dawn-Crowned",
            "Hisoka, Minamo Sensei",
            "Hixus, Prison Warden",
            "Hofri Ghostforge",
            "Hogaak, Arisen Necropolis",
            "Hokori, Dust Drinker",
            "Homura's Essence",
            "Homura, Human Ascendant",
            "Hope of Ghirapur",
            "Horde of Notions",
            "Horobi, Death's Wail",
            "Hua Tuo, Honored Physician",
            "Hythonia the Cruel",
            "Ib Halfheart, Goblin Tactician",
            "Ich-Tekik, Salvage Splicer",
            "Ichiga, Who Topples Oaks",
            "Icingdeath, Frost Tyrant",
            "Ihsan's Shade",
            "Iizuka the Ruthless",
            "Ikra Shidiqi, the Usurper",
            "Ilharg, the Raze-Boar",
            "Illuminor Szeras",
            "Illuna, Apex of Wishes",
            "Imaryll, Elfhame Elite",
            "Imbraham, Dean of Theory",
            "Imoen, Mystic Trickster",
            "Imoti, Celebrant of Bounty",
            "Inalla, Archmage Ritualist",
            "Iname as One",
            "Iname, Death Aspect",
            "Iname, Life Aspect",
            "Infernal Kirin",
            "Inferno of the Star Mounts",
            "Inga Rune-Eyes",
            "Ink-Eyes, Servant of Oni",
            "Inquisitor Eisenhorn",
            "Intet, the Dreamer",
            "Iona, Shield of Emeria",
            "Iroas, God of Victory",
            "Isamaru, Hound of Konda",
            "Isao, Enlightened Bushi",
            "Isareth the Awakener",
            "Ishai, Ojutai Dragonspeaker",
            "Ishi-Ishi, Akki Crackshot",
            "Ishkanah, Grafwidow",
            "Isperia the Inscrutable",
            "Isperia, Supreme Judge",
            "Isshin, Two Heavens as One",
            "Ith, High Arcanist",
            "Ivy, Gleeful Spellthief",
            "Iwamori of the Open Fist",
            "Iymrith, Desert Doom",
            "Izoni, Thousand-Eyed",
            "Jace, Vryn's Prodigy",
            "Jacob Hauken, Inspector",
            "Jadar, Ghoulcaller of Nephalia",
            "Jadzi, Oracle of Arcavios",
            "Jaheira, Friend of the Forest",
            "Jalira, Master Polymorphist",
            "Jan Jansen, Chaos Crafter",
            "Jarad, Golgari Lich Lord",
            "Jaraku the Interloper",
            "Jared Carthalion, True Heir",
            "Jareth, Leonine Titan",
            "Jasmine Boreal",
            "Jaxis, the Troublemaker",
            "Jaya Ballard, Task Mage",
            "Jazal Goldmane",
            "Jedit Ojanen of Efrava",
            "Jegantha, the Wellspring",
            "Jeleva, Nephalia's Scourge",
            "Jenara, Asura of War",
            "Jenson Carthalion, Druid Exile",
            "Jerren, Corrupted Bishop",
            "Jetmir, Nexus of Revels",
            "Jhoira of the Ghitu",
            "Jhoira, Ageless Innovator",
            "Jhoira, Weatherlight Captain",
            "Jin-Gitaxias, Core Augur",
            "Jin-Gitaxias, Progress Tyrant",
            "Jinnie Fay, Jetmir's Second",
            "Jirina Kudro",
            "Jiwari, the Earth Aflame",
            "Jodah, Archmage Eternal",
            "Jodah, the Unifier",
            "Jolene, the Plunder Queen",
            "Jolrael, Empress of Beasts",
            "Jolrael, Mwonvuli Recluse",
            "Jon Irenicus, Shattered One",
            "Jor Kadeen, the Prevailer",
            "Jori En, Ruin Diver",
            "Jorn, God of Winter",
            "Josu Vess, Lich Knight",
            "Judith, the Scourge Diva",
            "Jugan, the Rising Star",
            "Junji, the Midnight Sky",
            "Juri, Master of the Revue",
            "K'rrik, Son of Yawgmoth",
            "Kaalia of the Vast",
            "Kaalia, Zenith Seeker",
            "Kadena, Slinking Sorcerer",
            "Kaervek the Merciless",
            "Kaervek, the Spiteful",
            "Kagemaro, First to Suffer",
            "Kagha, Shadow Archdruid",
            "Kaheera, the Orphanguard",
            "Kaho, Minamo Historian",
            "Kaima, the Fractured Calm",
            "Kairi, the Swirling Sky",
            "Kaiso, Memory of Loyalty",
            "Kalain, Reclusive Painter",
            "Kalamax, the Stormsire",
            "Kalemne, Disciple of Iroas",
            "Kalitas, Bloodchief of Ghet",
            "Kalitas, Traitor of Ghet",
            "Kamahl, Heart of Krosa",
            "Kamahl, Pit Fighter",
            "Kambal, Consul of Allocation",
            "Kamber, the Plunderer",
            "Kami of the Crescent Moon",
            "Kamiz, Obscura Oculus",
            "Kangee, Sky Warden",
            "Karador, Ghost Chieftain",
            "Karametra, God of Harvests",
            "Karazikar, the Eye Tyrant",
            "Kardur, Doomscourge",
            "Kari Zev, Skyship Raider",
            "Karlach, Fury of Avernus",
            "Karlov of the Ghost Council",
            "Karrthus, Tyrant of Jund",
            "Kaseto, Orochi Archmage",
            "Kataki, War's Wage",
            "Kathril, Aspect Warper",
            "Katilda, Dawnhart Martyr",
            "Katilda, Dawnhart Prime",
            "Katsumasa, the Animator",
            "Kaza, Roil Chaser",
            "Kazarov, Sengir Pureblood",
            "Kazuul, Tyrant of the Cliffs",
            "Kediss, Emberclaw Familiar",
            "Kefnet the Mindful",
            "Keiga, the Tide Star",
            "Keleth, Sunmane Familiar",
            "Kelsien, the Plague",
            "Kemba, Kha Regent",
            "Kenrith, the Returned King",
            "Kentaro, the Smiling Cat",
            "Kenzo the Hardhearted",
            "Keranos, God of Storms",
            "Keruga, the Macrosage",
            "Keskit, the Flesh Sculptor",
            "Kess, Dissident Mage",
            "Kestia, the Cultivator",
            "Kethis, the Hidden Hand",
            "Khorvath Brightflame",
            "Kh?rn the Betrayer",
            "Kianne, Dean of Substance",
            "Kiki-Jiki, Mirror Breaker",
            "Kiku, Night's Flower",
            "Killian, Ink Duelist",
            "King Darien XLVIII",
            "King Macar, the Gold-Cursed",
            "Kinnan, Bonder Prodigy",
            "Kira, Great Glass-Spinner",
            "Kitt Kanto, Mayhem Diva",
            "Kiyomaro, First to Stand",
            "Klauth, Unrivaled Ancient",
            "Klothys, God of Destiny",
            "Kodama of the Center Tree",
            "Kodama of the East Tree",
            "Kodama of the North Tree",
            "Kodama of the South Tree",
            "Kodama of the West Tree",
            "Kogla, the Titan Ape",
            "Kokusho, the Evening Star",
            "Kolaghan, the Storm's Fury",
            "Koll, the Forgemaster",
            "Kolvori, God of Kinship",
            "Koma, Cosmos Serpent",
            "Konda, Lord of Eiganjo",
            #"Kongming, "Sleeping Dragon""#,
            "Kopala, Warden of Waves",
            "Korlash, Heir to Blackblade",
            "Korlessa, Scale Singer",
            "Kosei, Penitent Warlord",
            "Kothophed, Soul Hoarder",
            "Kotori, Pilot Prodigy",
            "Kotose, the Silent Spider",
            "Kozilek, Butcher of Truth",
            "Kozilek, the Great Distortion",
            "Krark, the Thumbless",
            "Kraum, Ludevic's Opus",
            "Krav, the Unredeemed",
            "Krenko, Mob Boss",
            "Krenko, Tin Street Kingpin",
            "Kresh the Bloodbraided",
            "Krond the Dawn-Clad",
            "Kros, Defense Contractor",
            "Krothuss, Lord of the Deep",
            "Kroxa, Titan of Death's Hunger",
            "Kruphix, God of Horizons",
            "Krydle of Baldur's Gate",
            "Kumano, Master Yamabushi",
            "Kumena, Tyrant of Orazca",
            "Kunoros, Hound of Athreos",
            "Kuon's Essence",
            "Kuon, Ogre Ascendant",
            "Kura, the Boundless Sky",
            "Kurbis, Harvest Celebrant",
            "Kurkesh, Onakke Ancient",
            "Kuro, Pitlord",
            "Kwain, Itinerant Meddler",
            "Kwende, Pride of Femeref",
            "Kydele, Chosen of Kruphix",
            "Kykar, Wind's Fury",
            "Kyler, Sigardian Emissary",
            "Kynaios and Tiro of Meletis",
            "Kyodai, Soul of Kamigawa",
            "Kyoki, Sanity's Eclipse",
            "Kytheon, Hero of Akros",
            "Lae'zel, Vlaakith's Champion",
            "Laelia, the Blade Reforged",
            "Lagomos, Hand of Hatred",
            "Lagrella, the Magpie",
            "Lathiel, the Bounteous Dawn",
            "Lathliss, Dragon Queen",
            "Lathril, Blade of the Elves",
            "Laurine, the Diversion",
            "Lavinia of the Tenth",
            "Lavinia, Azorius Renegade",
            "Lazav, Dimir Mastermind",
            "Lazav, the Multifarious",
            "Leinore, Autumn Sovereign",
            "Lena, Selfless Champion",
            "Leovold, Emissary of Trest",
            "Licia, Sanguine Tribune",
            "Lier, Disciple of the Drowned",
            "Liesa, Forgotten Archangel",
            "Liesa, Shroud of Dusk",
            "Light-Paws, Emperor's Voice",
            "Liliana, Heretical Healer",
            "Lim-D?l the Necromancer",
            "Linden, the Steadfast Queen",
            "Linessa, Zephyr Mage",
            "Linvala, Keeper of Silence",
            "Linvala, Shield of Sea Gate",
            "Linvala, the Preserver",
            "Lisette, Dean of the Root",
            "Livaan, Cultist of Tiamat",
            "Livio, Oathsworn Sentinel",
            "Lonis, Cryptozoologist",
            "Lorcan, Warlock Collector",
            "Lord Xander, the Collector",
            "Lorthos, the Tidemaker",
            "Losheel, Clockwork Scholar",
            "Lovisa Coldeyes",
            "Lozhan, Dragons' Legacy",
            "Lu Xun, Scholar General",
            "Lucius the Eternal",
            "Ludevic, Necro-Alchemist",
            "Ludevic, Necrogenius",
            "Lulu, Loyal Hollyphant",
            "Lurrus of the Dream-Den",
            "Lutri, the Spellchaser",
            "Lynde, Cheerful Tormentor",
            "Lyra Dawnbringer",
            "Lyzolda, the Blood Witch",
            "Maelstrom Wanderer",
            "Maeve, Insidious Singer",
            "Maga, Traitor to Mortals",
            "Magda, Brazen Outlaw",
            "Magnus the Red",
            "Mahadi, Emporium Master",
            "Mairsil, the Pretender",
            "Maja, Bretagard Protector",
            "Malcolm, Keen-Eyed Navigator",
            "Malfegor",
            "Mangara of Corondor",
            "Mangara, the Diplomat",
            "Mannichi, the Fevered Dream",
            "Maralen of the Mornsong",
            "Marath, Will of the Wild",
            "Marchesa, the Black Rose",
            "Mari, the Killing Quill",
            "Marisi, Breaker of the Coil",
            "Marrow-Gnawer",
            "Marwyn, the Nurturer",
            "Masako the Humorless",
            "Massacre Girl",
            "Masumaro, First to Live",
            "Mathas, Fiend Seeker",
            "Mavinda, Students' Advocate",
            "Mavren Fein, Dusk Apostle",
            "Mayael the Anima",
            "Mazirek, Kraul Death Priest",
            "Mazzy, Truesword Paladin",
            "Medomai the Ageless",
            "Melek, Izzet Paragon",
            "Melira, Sylvok Outcast",
            "Meloku the Clouded Mirror",
            "Memnarch",
            "Meren of Clan Nel Toth",
            "Meria, Scholar of Antiquity",
            "Merieke Ri Berit",
            "Miara, Thorn of the Glade",
            "Michiko Konda, Truth Seeker",
            "Miirym, Sentinel Wyrm",
            "Mikaeus, the Lunarch",
            "Mikaeus, the Unhallowed",
            "Mila, Crafty Companion",
            "Millicent, Restless Revenant",
            "Mina and Denn, Wildborn",
            "Minn, Wily Illusionist",
            "Minsc, Beloved Ranger",
            "Minthara, Merciless Soul",
            "Mirko Vosk, Mind Drinker",
            "Mirri the Cursed",
            "Mirri, Cat Warrior",
            "Mirri, Weatherlight Duelist",
            "Mishra, Artificer Prodigy",
            "Mistform Ultimus",
            "Mizzix of the Izmagnus",
            "Mogis, God of Slaughter",
            "Moira, Urborg Haunt",
            "Molimo, Maro-Sorcerer",
            "Momir Vig, Simic Visionary",
            "Moraug, Fury of Akoum",
            "Moritte of the Frost",
            "Morophon, the Boundless",
            "Mortarion, Daemon Primarch",
            "Mowu, Loyal Companion",
            "Mr. Orfeo, the Boulder",
            "Muldrotha, the Gravetide",
            "Multani, Yavimaya's Avatar",
            "Munda, Ambush Leader",
            "Muzzio, Visionary Architect",
            "Myojin of Blooming Dawn",
            "Myojin of Cleansing Fire",
            "Myojin of Cryptic Dreams",
            "Myojin of Grim Betrayal",
            "Myojin of Infinite Rage",
            "Myojin of Life's Web",
            "Myojin of Night's Reach",
            "Myojin of Roaring Blades",
            "Myojin of Seeing Winds",
            "Myojin of Towering Might",
            "Myrkul, Lord of Bones",
            "Naban, Dean of Iteration",
            "Nadaar, Selfless Paladin",
            "Nadier, Agent of the Duskenel",
            "Nael, Avizoa Aeronaut",
            "Nagao, Bound by Honor",
            "Najal, the Storm Runner",
            "Najeela, the Blade-Blossom",
            "Nalia de'Arnise",
            "Naomi, Pillar of Order",
            "Narfi, Betrayer King",
            "Narset, Enlightened Master",
            "Naru Meha, Master Wizard",
            "Nashi, Moon Sage's Scion",
            "Nassari, Dean of Expression",
            "Nath of the Gilt-Leaf",
            "Nazahn, Revered Bladesmith",
            "Neera, Wild Mage",
            "Nefarox, Overlord of Grixis",
            "Neheb, Dreadhorde Champion",
            "Neheb, the Eternal",
            "Neheb, the Worthy",
            "Nekusar, the Mindrazer",
            "Nemata, Primeval Warden",
            "Nethroi, Apex of Death",
            "Nevinyrral, Urborg Tyrant",
            "Neyam Shai Murad",
            "Nezahal, Primal Tide",
            "Niambi, Esteemed Speaker",
            "Niambi, Faithful Healer",
            "Nicol Bolas",
            "Nicol Bolas, the Ravager",
            "Nighteyes the Desecrator",
            "Nihiloor",
            "Nikara, Lair Scavenger",
            "Nikya of the Old Ways",
            "Nils, Discipline Enforcer",
            "Nin, the Pain Artist",
            "Nine-Fingers Keene",
            "Nissa, Vastwood Seer",
            "Niv-Mizzet Reborn",
            "Niv-Mizzet, Dracogenius",
            "Niv-Mizzet, Parun",
            "Niv-Mizzet, the Firemind",
            "Nogi, Draco-Zealot",
            "Norika Yamazaki, the Poet",
            "Norin the Wary",
            "Noyan Dar, Roil Shaper",
            "Numa, Joraga Chieftain",
            "Numot, the Devastator",
            "Nylea, God of the Hunt",
            "Nylea, Keen-Eyed",
            "Nymris, Oona's Trickster",
            "O-Kagachi, Vengeful Kami",
            "Ob Nixilis, Unshackled",
            "Ob Nixilis, the Fallen",
            "Obeka, Brute Chronologist",
            "Obosh, the Preypiercer",
            "Obuun, Mul Daya Ancestor",
            "Obzedat, Ghost Council",
            "Octavia, Living Thesis",
            "Odric, Blood-Cursed",
            "Odric, Lunarch Marshal",
            "Odric, Master Tactician",
            "Ognis, the Dragon's Lash",
            "Oji, the Exquisite Blade",
            "Ojutai, Soul of Winter",
            "Okaun, Eye of Chaos",
            "Oketra the True",
            "Olag, Ludevic's Hubris",
            "Old Gnawbone",
            "Old One Eye",
            "Old Rutstein",
            "Old Stickfingers",
            "Olivia Voldaren",
            "Olivia, Crimson Bride",
            "Olivia, Mobilized for War",
            "Oloro, Ageless Ascetic",
            "Omnath, Locus of Creation",
            "Omnath, Locus of Mana",
            "Omnath, Locus of Rage",
            "Omnath, Locus of the Roil",
            "Oona, Queen of the Fae",
            "Opal-Eye, Konda's Yojimbo",
            "Orah, Skyclave Hierophant",
            "Orcus, Prince of Undeath",
            "Oriss, Samite Guardian",
            "Ormendahl, Profane Prince",
            "Ormendahl, the Corrupter",
            "Oros, the Avenger",
            "Orvar, the All-Form",
            "Osgir, the Reconstructor",
            "Oskar, Rubbish Reclaimer",
            "Oswald Fiddlebender",
            "Otrimi, the Ever-Playful",
            "Oviya Pashiri, Sage Lifecrafter",
            "Oyobi, Who Split the Heavens",
            "Padeem, Consul of Innovation",
            "Pako, Arcane Retriever",
            "Palladia-Mors, the Ruiner",
            "Parnesse, the Subtle Brush",
            "Pashalik Mons",
            "Patron of the Akki",
            "Patron of the Kitsune",
            "Patron of the Moon",
            "Patron of the Nezumi",
            "Patron of the Orochi",
            "Perrie, the Pulverizer",
            "Phabine, Boss's Confidant",
            "Phage the Untouchable",
            "Pharika, God of Affliction",
            "Phenax, God of Deception",
            "Phylath, World Sculptor",
            "Pia Nalaar",
            "Pia and Kiran Nalaar",
            "Pir, Imaginative Rascal",
            "Piru, the Volatile",
            "Plargg, Dean of Chaos",
            "Polukranos, Unchained",
            "Polukranos, World Eater",
            "Pramikon, Sky Rampart",
            "Prava of the Steel Legion",
            "Prime Speaker Vannifar",
            "Prime Speaker Zegana",
            "Progenitus",
            "Prosper, Tome-Bound",
            "Prossh, Skyraider of Kher",
            "Purphoros, Bronze-Blooded",
            "Purphoros, God of the Forge",
            "Queen Allenal of Ruadach",
            "Queen Marchesa",
            "Questing Beast",
            "Queza, Augur of Agonies",
            "Quintorius, Field Historian",
            "Radha, Coalition Warlord",
            "Radha, Heart of Keld",
            "Radha, Heir to Keld",
            "Radiant, Serra Archangel",
            "Raff Capashen, Ship's Mage",
            "Raff, Weatherlight Stalwart",
            "Raffine, Scheming Seer",
            "Rafiq of the Many",
            "Ragavan, Nimble Pilferer",
            "Raggadragga, Goreguts Boss",
            "Raiyuu, Storm's Edge",
            "Rakdos the Defiler",
            "Rakdos, Lord of Riots",
            "Rakdos, the Showstopper",
            "Rakka Mar",
            "Raksha Golden Cub",
            "Ramos, Dragon Engine",
            "Ranar the Ever-Watchful",
            "Rankle, Master of Pranks",
            "Raphael, Fiendish Savior",
            "Rasaad yn Bashir",
            "Rashmi, Eternities Crafter",
            "Ratadrabik of Urborg",
            "Ravos, Soultender",
            "Rayami, First of the Fallen",
            "Razaketh, the Foulblooded",
            "Razia, Boros Archangel",
            "Reaper King",
            "Rebbec, Architect of Ascension",
            "Regna, the Redeemer",
            "Reidane, God of the Worthy",
            "Reki, the History of Kamigawa",
            "Rem Karolus, Stalwart Slayer",
            "Renari, Merchant of Marvels",
            "Renata, Called to the Hunt",
            "Reya Dawnbringer",
            "Reyav, Master Smith",
            "Reyhan, Last of the Abzan",
            "Rhoda, Geist Avenger",
            "Rhonas the Indomitable",
            "Rhys the Exiled",
            "Rhys the Redeemed",
            "Rielle, the Everwise",
            "Rienne, Angel of Rebirth",
            "Rigo, Streetwise Mentor",
            "Riku of Two Reflections",
            "Rilsa Rael, Kingpin",
            "Rin and Seri, Inseparable",
            "Rionya, Fire Dancer",
            "Rishkar, Peema Renegade",
            "Risona, Asari Commander",
            "Rith, Liberated Primeval",
            "Rith, the Awakener",
            "Rivaz of the Claw",
            "Roalesk, Apex Hybrid",
            "Rocco, Cabaretti Caterer",
            "Rograkh, Son of Rohgahh",
            "Rona, Disciple of Gix",
            "Rona, Sheoldred's Faithful",
            "Roon of the Hidden Realm",
            "Rootha, Mercurial Artist",
            "Rorix Bladewing",
            "Rosheen Meanderer",
            "Rosnakht, Heir of Rohgahh",
            "Rubinia Soulsinger",
            "Ruhan of the Fomori",
            "Rulik Mons, Warren Chief",
            "Rune-Tail's Essence",
            "Rune-Tail, Kitsune Ascendant",
            "Runo Stromkirk",
            "Ruric Thar, the Unbowed",
            "Ruxa, Patient Professor",
            "Ryusei, the Falling Star",
            "Sachi, Daughter of Seshiro",
            "Safana, Calimport Cutthroat",
            "Saffi Eriksdotter",
            "Sai, Master Thopterist",
            "Sakashima of a Thousand Faces",
            "Sakashima the Impostor",
            "Sakiko, Mother of Summer",
            "Samut, Voice of Dissent",
            "Sapling of Colfenor",
            "Sarevok, Deathbringer",
            "Sarulf, Realm Eater",
            "Saryth, the Viper's Fang",
            "Sasaya's Essence",
            "Sasaya, Orochi Ascendant",
            "Saskia the Unyielding",
            "Satoru Umezawa",
            "Satsuki, the Living Lore",
            "Savra, Queen of the Golgari",
            "Scarmaker",
            "Scion of the Ur-Dragon",
            "Sedris, the Traitor King",
            "Sefris of the Hidden Ways",
            "Seizan, Perverter of Truth",
            "Sek'Kuar, Deathkeeper",
            "Sekki, Seasons' Guide",
            "Selvala, Explorer Returned",
            "Selvala, Heart of the Wilds",
            "Sen Triplets",
            "Sengir, the Dark Baron",
            "Sensei Golden-Tail",
            "Sephara, Sky's Blade",
            "Seshiro the Anointed",
            "Sevinne, the Chronoclasm",
            "Shabraz, the Skyshark",
            "Shadowheart, Dark Justiciar",
            "Shadrix Silverquill",
            "Shaile, Dean of Radiance",
            "Shalai, Voice of Plenty",
            "Shanid, Sleepers' Scourge",
            "Shanna, Purifying Blade",
            "Shanna, Sisay's Legacy",
            "Sharuum the Hegemon",
            "Shattergang Brothers",
            "Sheoldred, Whispering One",
            "Sheoldred, the Apocalypse",
            "Shessra, Death's Whisper",
            "Shidako, Broodmistress",
            "Shigeki, Jukai Visionary",
            "Shimatsu the Bloodcloaked",
            "Shirei, Shizo's Caretaker",
            "Shisato, Whispering Hunter",
            "Shizuko, Caller of Autumn",
            "Shu Yun, the Silent Tempest",
            "Siani, Eye of the Storm",
            "Sidar Kondo of Jamuraa",
            "Sidisi, Brood Tyrant",
            "Sidisi, Undead Vizier",
            "Sigarda, Champion of Light",
            "Sigarda, Heron's Grace",
            "Sigarda, Host of Herons",
            "Sigrid, God-Favored",
            "Silas Renn, Seeker Adept",
            "Silumgar, the Drifting Death",
            "Silvar, Devourer of the Free",
            "Silvos, Rogue Elemental",
            "Siona, Captain of the Pyleas",
            "Sisay, Weatherlight Captain",
            "Sisters of Stone Death",
            "Sivriss, Nightmare Speaker",
            "Skanos Dragonheart",
            "Skithiryx, the Blight Dragon",
            "Skullbriar, the Walking Grave",
            "Skyfire Kirin",
            "Slimefoot, the Stowaway",
            "Slinn Voda, the Rising Deep",
            "Sliver Hivelord",
            "Sliver Legion",
            "Slobad, Goblin Tinkerer",
            "Slogurk, the Overslime",
            "Slurrk, All-Ingesting",
            "Snapdax, Apex of the Hunt",
            "Sol'kanar the Swamp King",
            "Sol'kanar the Tainted",
            "Soramaro, First to Dream",
            "Sosuke, Son of Seshiro",
            "Soul of Windgrace",
            "Squee, Dubious Monarch",
            "Squee, Goblin Nabob",
            "Squee, the Immortal",
            "Sram, Senior Edificer",
            "Stabwhisker the Odious",
            "Stangg",
            "Stenn, Paranoid Partisan",
            "Stitcher Geralf",
            "Stonebrow, Krosan Hero",
            "Storrev, Devkarin Lich",
            "Storvald, Frost Giant Jarl",
            "Strefan, Maurer Progenitor",
            "Subira, Tulzidi Caravanner",
            "Surrak Dragonclaw",
            "Surrak, the Hunt Caller",
            "Svella, Ice Shaper",
            "Svyelun of Sea and Sky",
            "Sydri, Galvanic Genius",
            "Sygg, River Cutthroat",
            "Sygg, River Guide",
            "Sylvia Brightspear",
            "Syr Alin, the Lion's Claw",
            "Syr Carah, the Bold",
            "Syr Elenora, the Discerning",
            "Syr Faren, the Hengehammer",
            "Syr Konrad, the Grim",
            "Syrix, Carrier of the Flame",
            "Sythis, Harvest's Hand",
            "Szadek, Lord of Secrets",
            "Taborax, Hope's Demise",
            "Tahngarth, First Mate",
            "Taigam, Ojutai Master",
            "Taigam, Sidisi's Hand",
            "Tajic, Blade of the Legion",
            "Tajic, Legion's Edge",
            "Takeno, Samurai General",
            "Talrand, Sky Summoner",
            "Tameshi, Reality Architect",
            "Tana, the Bloodsower",
            "Tanazir Quandrix",
            "Taranika, Akroan Veteran",
            "Targ Nar, Demon-Fang Gnoll",
            "Tariel, Reckoner of Souls",
            "Tarox Bladewing",
            "Tasigur, the Golden Fang",
            "Tatsunari, Toad Rider",
            "Tatyova, Benthic Druid",
            "Tatyova, Steward of Tides",
            "Tawnos, Urza's Apprentice",
            "Tayam, Luminous Enigma",
            "Tazri, Beacon of Unity",
            "Teferi, Mage of Zhalfir",
            "Temmet, Vizier of Naktamun",
            "Teneb, the Harvester",
            "Tergrid, God of Fright",
            "Teshar, Ancestor's Apostle",
            "Tetsuko Umezawa, Fugitive",
            "Tetzimoc, Primal Death",
            "Teysa Karlov",
            "Teysa, Envoy of Ghosts",
            "Teysa, Orzhov Scion",
            "Thada Adel, Acquisitor",
            "Thalia, Guardian of Thraben",
            "Thalia, Heretic Cathar",
            "Thalisse, Reverent Medium",
            "Thantis, the Warweaver",
            "Thassa, Deep-Dwelling",
            "Thassa, God of the Sea",
            "The Beamtown Bullies",
            "The Council of Four",
            "The First Sliver",
            "The Gitrog Monster",
            "The Haunt of Hightower",
            "The Locust God",
            "The Mimeoplasm",
            "The Peregrine Dynamo",
            "The Prismatic Piper",
            "The Raven Man",
            "The Reality Chip",
            "The Red Terror",
            "The Scarab God",
            "The Scorpion God",
            "The Tarrasque",
            "The Unspeakable",
            "The Ur-Dragon",
            "Thelon of Havenwood",
            "Thrakkus the Butcher",
            "Thrasios, Triton Hero",
            "Thrasta, Tempest's Roar",
            "Thraximundar",
            "Thromok the Insatiable",
            "Thrun, the Last Troll",
            "Thryx, the Sudden Storm",
            "Tiamat",
            "Tiana, Ship's Caretaker",
            "Tibor and Lumia",
            "Timin, Youthful Geist",
            "Timothar, Baron of Bats",
            "Tishana, Voice of Thunder",
            "Titania, Protector of Argoth",
            "Tivadar of Thorn",
            "Tivash, Gloom Summoner",
            "Tivit, Seller of Secrets",
            "Tobita, Master of Winds",
            "Toggo, Goblin Weaponsmith",
            "Tok-Tok, Volcano Born",
            "Tolsimir Wolfblood",
            "Tolsimir, Friend to Wolves",
            "Toluz, Clever Conductor",
            "Tomik, Distinguished Advokist",
            "Tomorrow, Azami's Familiar",
            "Tomoya the Revealer",
            "Toothy, Imaginary Friend",
            "Toralf, God of Fury",
            "Torbran, Thane of Red Fell",
            "Torens, Fist of the Angels",
            "Torgaar, Famine Incarnate",
            "Tori D'Avenant, Fury Rider",
            "Tormod, the Desecrator",
            "Toshiro Umezawa",
            "Toski, Bearer of Secrets",
            "Tourach, Dread Cantor",
            "Tovolar, Dire Overlord",
            "Tovolar, the Midnight Scourge",
            "Toxrill, the Corrosive",
            "Traxos, Scourge of Kroog",
            "Trazyn the Infinite",
            "Trelasarra, Moon Dancer",
            "Treva, the Renewer",
            "Triad of Fates",
            "Tromokratis",
            "Trostani Discordant",
            "Trostani, Selesnya's Voice",
            "Trynn, Champion of Freedom",
            "Tuktuk the Explorer",
            "Tura Kenner?d, Skyknight",
            "Tuvasa the Sunlit",
            "Tuya Bearclaw",
            "Tymaret, Chosen from Death",
            "Tymaret, the Murder King",
            "Tymna the Weaver",
            "Ukkima, Stalking Shadow",
            "Ulamog, the Ceaseless Hunger",
            "Vela the Night-Clad",
            "Velomachus Lorehold",
            "Vendilion Clique",
            "Venser, Shaper Savant",
            "Verazol, the Split Current",
            "Verdeloth the Ancient",
            "Verix Bladewing",
            "Verrak, Warped Sengir",
            "Veyran, Voice of Duality",
            "Vhal, Candlekeep Researcher",
            "Vhati il-Dal",
            "Vial Smasher the Fierce",
            "Viconia, Drow Apostate",
            "Vilis, Broker of Blood",
            "Virtus the Veiled",
            "Visara the Dreadful",
            "Vish Kal, Blood Arbiter",
            "Vito, Thorn of the Dusk Rose",
            "Vogar, Necropolis Tyrant",
            "Vohar, Vodalian Desecrator",
            "Volo, Guide to Monsters",
            "Volo, Itinerant Scholar",
            "Volrath, the Shapestealer",
            "Vona, Butcher of Magan",
            "Vorel of the Hull Clade",
            "Vorinclex, Monstrous Raider",
            "Vorinclex, Voice of Hunger",
            "Vorosh, the Hunter",
            "Vrondiss, Rage of Ancients",
            "Wasitora, Nekoru Queen",
            "Whisper, Blood Liturgist",
            "Wilhelt, the Rotcleaver",
            "Willowdusk, Essence Seer",
            "Wilson, Refined Grizzly",
            "Winota, Joiner of Forces",
            "Withengar Unbound",
            "Wort, Boggart Auntie",
            "Wort, the Raidmother",
            "Wrexial, the Risen Deep",
            "Wulfgar of Icewind Dale",
            "Wydwen, the Biting Gale",
            "Wyleth, Soul of Steel",
            "Wyll, Blade of Frontiers",
            "Xanathar, Guild Kingpin",
            "Xantcha, Sleeper Agent",
            "Xenagos, God of Revels",
            "Xyris, the Writhing Storm",
            "Yahenni, Undying Partisan",
            "Yannik, Scavenging Sentinel",
            "Yargle, Glutton of Urborg",
            "Yarok, the Desecrated",
            "Yasharn, Implacable Earth",
            "Yasova Dragonclaw",
            "Yawgmoth, Thran Physician",
            "Yedora, Grave Gardener",
            "Yennett, Cryptic Sovereign",
            "Yeva, Nature's Herald",
            "Yidaro, Wandering Monster",
            "Yidris, Maelstrom Wielder",
            "Yisan, the Wanderer Bard",
            "Yomiji, Who Bars the Way",
            "Yorion, Sky Nomad",
            "Yorvo, Lord of Garenbrig",
            "Yosei, the Morning Star",
            "Yoshimaru, Ever Faithful",
            "Yukora, the Prisoner",
            "Yuriko, the Tiger's Shadow",
            "Yurlok of Scorch Thrash",
            "Yusri, Fortune's Flame",
            "Zabaz, the Glimmerwasp",
            "Zacama, Primal Calamity",
            "Zada, Hedron Grinder",
            "Zaffai, Thunder Conductor",
            "Zagras, Thief of Heartbeats",
            "Zahid, Djinn of the Lamp",
            "Zalto, Fire Giant Duke",
            "Zamriel, Seraph of Steel",
            "Zar Ojanen, Scion of Efrava",
            "Zara, Renegade Recruiter",
            "Zareth San, the Trickster",
            "Zaxara, the Exemplary",
            "Zedruu the Greathearted",
            "Zegana, Utopian Speaker",
            "Zellix, Sanity Flayer",
            "Zeriam, Golden Wind",
            "Zetalpa, Primal Dawn",
            "Zevlor, Elturel Exile",
            "Ziatora, the Incinerator",
            "Zilortha, Strength Incarnate",
            "Zimone, Quandrix Prodigy",
            "Zirda, the Dawnwaker",
            "Zndrsplt, Eye of Wisdom",
            "Zo-Zu the Punisher",
            "Zur the Enchanter",
            "Zur, Eternal Schemer",
            "Zurgo Bellstriker",
            "Zurgo Helmsmasher",
            "Zurzoth, Chaos Rider",
        ]
        return cmdList
    }*/

}
